source 'https://github.com/CocoaPods/Specs.git'

target 'LEAlertController', :exclusive => true do
  pod "LEAlertController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LEAlertController", :path => "../"

  
end
